version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1

  redis:
    image: redis:7.2-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    restart: unless-stopped
    volumes:
      - redis-data:/data
