"""Initial schema

Revision ID: 4076b76d163e
Revises: 
Create Date: 2025-04-30 21:18:57.307800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from models import allocator

# revision identifiers, used by Alembic.
revision: str = '4076b76d163e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', allocator.UUID_F(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('in_stock', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', allocator.UUID_F(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.Enum('admin', 'user', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_product_requests',
    sa.Column('id', allocator.UUID_F(), nullable=False),
    sa.Column('user_id', allocator.UUID_F(), nullable=False),
    sa.Column('product_id', allocator.UUID_F(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'product_id', name='uq_user_product')
    )
    op.create_index('ix_user_product', 'user_product_requests', ['user_id', 'product_id'], unique=False)
    op.create_index(op.f('ix_user_product_requests_product_id'), 'user_product_requests', ['product_id'], unique=False)
    op.create_index(op.f('ix_user_product_requests_user_id'), 'user_product_requests', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_product_requests_user_id'), table_name='user_product_requests')
    op.drop_index(op.f('ix_user_product_requests_product_id'), table_name='user_product_requests')
    op.drop_index('ix_user_product', table_name='user_product_requests')
    op.drop_table('user_product_requests')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
